[package]
name = "postdata-desktop"
version = "0.10.202"
description = "Postdata is a Git-integrated, fully offline, and open-source API client"
authors = ["Steven <steven@postdata.cn>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-updater = "2"
log = "0.4.22"
dashmap = "6.1.0"
tokio = { version = "1.40.0", features = ["macros"] }
tokio-util = "0.7.12"
thiserror = "2.0.9"
postdata-relay = { path = "../../hoppscotch-relay" }
tauri-plugin-async-wrapper = "0.1.2"
dirs = "5.0.1"
hex_color = "3.0.0"
tauri-plugin-window-state = "2.0.0"
tauri-plugin-store = "2.0.0"
anyhow = "1.0.95"
open = "5.3.2"
tracing = "0.1"
tracing-subscriber = "0.3"
dotenv = "0.15"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26.0"
objc = "0.2.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58.0", features = [
  "Win32_Graphics_Dwm",
  "Win32_Foundation",
  "Win32_UI_Controls",
] }
winver = "1"
